PlanLepszy/src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $info = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $course = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $type_of_course = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $semester = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): static
    {
        $this->info = $info;

        return $this;
    }

    public function getCourse(): ?string
    {
        return $this->course;
    }

    public function setCourse(?string $course): static
    {
        $this->course = $course;

        return $this;
    }

    public function getTypeOfCourse(): ?string
    {
        return $this->type_of_course;
    }

    public function setTypeOfCourse(?string $type_of_course): static
    {
        $this->type_of_course = $type_of_course;

        return $this;
    }

    public function getSemester(): ?string
    {
        return $this->semester;
    }

    public function setSemester(?string $semester): static
    {
        $this->semester = $semester;

        return $this;
    }
}

PlanLepszy/src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('info')
            ->add('course')
            ->add('type_of_course')
            ->add('semester')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

PlanLepszy/src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/')]
final class StudentController extends AbstractController
{
    #[Route(name: 'app_student_index', methods: ['GET'])]
    public function index(StudentRepository $studentRepository): Response
    {
        $studentRepository->find(2);
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_student_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('student/new.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_show', methods: ['GET'])]
    public function show(Student $student): Response
    {
        return $this->render('student/show.html.twig', [
            'student' => $student,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_student_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('student/edit.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_delete', methods: ['POST'])]
    public function delete(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
    }
}

PlanLepszy/templates/student/_delete_form.html.twig
<form method="post" action="{{ path('app_student_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn">Delete</button>
</form>

PlanLepszy/templates/student/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

PlanLepszy/templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student{% endblock %}

{% block body %}
    <h1>Edit Student</h1>

    {{ include('student/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_student_index') }}">back to list</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}

PlanLepszy/templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student index{% endblock %}

{% block body %}
    <h1>Student index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Info</th>
                <th>Course</th>
                <th>Type_of_course</th>
                <th>Semester</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.info }}</td>
                <td>{{ student.course }}</td>
                <td>{{ student.typeOfCourse }}</td>
                <td>{{ student.semester }}</td>
                <td>
                    <a href="{{ path('app_student_show', {'id': student.id}) }}">show</a>
                    <a href="{{ path('app_student_edit', {'id': student.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_student_new') }}">Create new</a>
{% endblock %}

PlanLepszy/templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Student{% endblock %}

{% block body %}
    <h1>Create new Student</h1>

    {{ include('student/_form.html.twig') }}

    <a href="{{ path('app_student_index') }}">back to list</a>
{% endblock %}

PlanLepszy/templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student{% endblock %}

{% block body %}
    <h1>Student</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>Info</th>
                <td>{{ student.info }}</td>
            </tr>
            <tr>
                <th>Course</th>
                <td>{{ student.course }}</td>
            </tr>
            <tr>
                <th>Type_of_course</th>
                <td>{{ student.typeOfCourse }}</td>
            </tr>
            <tr>
                <th>Semester</th>
                <td>{{ student.semester }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_student_index') }}">back to list</a>

    <a href="{{ path('app_student_edit', {'id': student.id}) }}">edit</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}